version: '3'
services:
  arangodb:
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=azim1383
    ports:
      - "8529:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3

volumes:
  arangodb-data:
